# We give a name to the workflow
name: lint and test workflow
# Define the events to trigger the workflow
on: push
# Define jobs
jobs:
  # Give a name to the job
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v3
      - name: install dependencies
        run: npm ci
      - name: lint
        run: npm run lint  
  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: get code
        uses: actions/checkout@v3
      - name: install dependencies
        run: npm ci
      - name: tests
        run: npm run test
  deployment:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: get code
        uses: actions/checkout@v3
      - name: get dependencies
        run: npm ci
      - name: build
        run: npm run build
      - name: deploy
        run: echo "Deploying app in steps"